version: '3.8'

services:
  mosquitto:
    build: ./mosquitto_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/check_mosquitto.sh"]
      interval: 1s
      timeout: 2s
      retries: 6

  frontend:
    build: ./webapp
    ports:
      - "8080:80"

  rule_engine:
    build: ./rule_engine
    depends_on:
      mosquitto:
        condition: service_healthy

volumes:
  mosquitto_data:
  mosquitto_log:
